channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - contextily
  - geopandas
  - jupyterlab
  - pip:
      - pysal==2
      - mapclassify 
      - git+https://github.com/geopandas/geopandas.git@master

